<?php
require_once __DIR__ . '/../../config.php';
$pageTitle = 'Дизайн приложений под ключ — заказать UI/UX дизайн | Bobr Studio';
$pageDesc = 'Профессиональный дизайн мобильных приложений под ключ. UI/UX дизайн для iOS и Android, прототипы, дизайн-системы, адаптация под экраны. Закажите дизайн приложения!';
$ogImage = '/img/svg/app-design.svg';
require_once __DIR__ . '/../../includes/header.php';
?>
<script type="application/ld+json">{ "@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Главная","item":"<?= SITE_URL ?>/"},{"@type":"ListItem","position":2,"name":"Дизайн приложений","item":"<?= SITE_URL ?>/app-design"}]}</script>
<script type="application/ld+json">{ "@context":"https://schema.org","@type":"Service","name":"Дизайн приложений под ключ","description":"UI/UX дизайн мобильных приложений для iOS и Android, прототипы, дизайн-системы.","provider":{"@type":"ProfessionalService","name":"Bobr Studio","url":"<?= SITE_URL ?>"},"areaServed":"RU","offers":{"@type":"Offer","price":"80000","priceCurrency":"RUB"}}</script>
	<section class="hero section-light"><canvas class="hero-particles" id="heroParticles" aria-hidden="true"></canvas><div class="container hero-grid"><div class="hero-content"><div class="slider-title">Профессиональный<h1>Дизайн <span class="text-accent">приложений</span> под ключ</h1>— UI/UX для iOS и Android</div><p class="slider-text">Создаём дизайн мобильных приложений, который любят пользователи. Прототипы, UI-дизайн, дизайн-системы, адаптация под экраны и платформы. Для стартапов и корпоративных проектов.</p><a href="#brief" class="btn btn-main">Заказать дизайн</a></div><div class="hero-image"><img src="/img/svg/app-design.svg" alt="Дизайн приложений под ключ" loading="eager" style="max-height:550px;width:auto"></div></div><div class="wave-divider wave-dark" aria-hidden="true"><svg viewBox="0 0 1200 60" preserveAspectRatio="none"><path d="M0,30 C150,55 350,5 600,30 C850,55 1050,5 1200,30 L1200,60 L0,60 Z"></path></svg></div></section>
	<section class="stages section-dark"><div class="container"><div class="section-title-wrap"><h2 class="section-title">Этапы дизайна</h2></div><div class="stages-grid">
		<div class="stage-card dev-etap"><div class="stage-num">01</div><div class="stage-icon"><img loading="lazy" src="/img/icons/analise.png" alt="Исследование"></div><h3 class="stage-title">Исследование</h3><ul><li>Анализируем продукт и аудиторию</li><li>Изучаем конкурентов</li><li>Собираем требования</li><li>Составляем CJM</li></ul></div>
		<div class="stage-card dev-etap"><div class="stage-num">02</div><div class="stage-icon"><img loading="lazy" src="/img/icons/plan.png" alt="Прототип"></div><h3 class="stage-title">Прототипирование</h3><ul><li>Wifeframe'ы всех экранов</li><li>Пользовательские сценарии</li><li>Навигация по приложению</li><li>Согласовываем логику</li></ul></div>
		<div class="stage-card dev-etap"><div class="stage-num">03</div><div class="stage-icon"><img loading="lazy" src="/img/icons/disign.png" alt="UI дизайн"></div><h3 class="stage-title">UI-дизайн</h3><ul><li>Дизайн всех экранов приложения</li><li>Адаптация под iOS и Android</li><li>Анимации интерфейса</li><li>Согласовываем макеты</li></ul></div>
		<div class="stage-card dev-etap"><div class="stage-num">04</div><div class="stage-icon"><img loading="lazy" src="/img/icons/adaptive.png" alt="Адаптив"></div><h3 class="stage-title">Адаптация</h3><ul><li>Под все размеры экранов</li><li>Тёмная и светлая тема</li><li>Локализация</li><li>Гайдлайны платформ</li></ul></div>
		<div class="stage-card dev-etap"><div class="stage-num">05</div><div class="stage-icon"><img loading="lazy" src="/img/icons/mobile.png" alt="Мокапы"></div><h3 class="stage-title">Дизайн-система</h3><ul><li>UI-кит и компоненты</li><li>Иконки и иллюстрации</li><li>Типографика и цвета</li><li>Передача в разработку</li></ul></div>
		<div class="stage-card dev-etap"><div class="stage-num">06</div><div class="stage-icon"><img loading="lazy" src="/img/icons/support.png" alt="Поддержка"></div><h3 class="stage-title">Сопровождение</h3><ul><li>Авторский надзор</li><li>Правки и доработки</li><li>Дизайн обновлений</li><li>Консультации</li></ul></div>
	</div></div><div class="wave-divider wave-light" aria-hidden="true"><svg viewBox="0 0 1200 60" preserveAspectRatio="none"><path d="M0,30 C150,55 350,5 600,30 C850,55 1050,5 1200,30 L1200,60 L0,60 Z"></path></svg></div></section>
	<section class="advantages section-light"><div class="container"><div class="section-title-wrap"><h3 class="section-title">Почему заказывают дизайн у нас?</h3></div><div class="adv-grid">
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/mobile.png" alt="iOS и Android"></div><h3 class="adv-title">iOS + Android</h3><p class="adv-text">проектируем под обе платформы с учётом гайдлайнов — Human Interface и Material Design</p></div>
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/start.png" alt="Прототипы"></div><h3 class="adv-title">Кликабельные прототипы</h3><p class="adv-text">рисунки Figma с анимациями — вы сразу видите, как будет работать приложение</p></div>
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/desctop.png" alt="Дизайн-система"></div><h3 class="adv-title">Готовая дизайн-система</h3><p class="adv-text">UI-кит со всеми компонентами — разработчики начинают вёрстку без вопросов</p></div>
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/money.png" alt="Конверсия"></div><h3 class="adv-title">UX под конверсию</h3><p class="adv-text">каждый экран прорабатываем с точки зрения бизнес-метрик и пользовательского опыта</p></div>
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/image.png" alt="Визуал"></div><h3 class="adv-title">Современный визуал</h3><p class="adv-text">минималистичный, чистый дизайн с акцентами — ваше приложение выглядит дорого</p></div>
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/support.png" alt="Поддержка"></div><h3 class="adv-title">Авторский надзор</h3><p class="adv-text">сопровождаем разработку, проверяем соответствие макетам и подсказываем по анимациям</p></div>
	</div></div><div class="wave-divider wave-dark" aria-hidden="true"><svg viewBox="0 0 1200 60" preserveAspectRatio="none"><path d="M0,30 C150,55 350,5 600,30 C850,55 1050,5 1200,30 L1200,60 L0,60 Z"></path></svg></div></section>
<?php $briefWave='wave-dark';$briefTitle='Бриф на дизайн приложения';$briefSubtitle='Расскажите о проекте — нарисуем';require __DIR__.'/../../briefs/app-design-brief.php';?>
<?php $noWave=true;require_once __DIR__.'/../../includes/tech-marquee.php';?>
<?php $pfDarkBg=true;$pfTitle='Наше портфолио';$pfSubtitle='Более 30 проектов';require_once __DIR__.'/../../includes/portfolio-block.php';?>
	<section class="price section-light"><div class="container"><div class="section-title-wrap"><h2 class="section-title">Стоимость дизайна приложений</h2><p class="section-subtitle">от сложности проекта</p></div><div class="price-grid">
		<div class="price-card"><h3 class="price-card-title">Базовый</h3><div class="price-value">от <strong>80 000</strong> ₽</div><ul class="price-features"><li>до 10 экранов</li><li>Прототип</li><li>UI-дизайн одной платформы</li><li>UI-кит</li></ul><a href="#brief" class="btn btn-main">Заказать</a></div>
		<div class="price-card price-card-featured"><h3 class="price-card-title">Стандарт</h3><div class="price-value">от <strong>150 000</strong> ₽</div><ul class="price-features"><li>до 30 экранов</li><li>iOS + Android</li><li>Анимации интерфейса</li><li>Тёмная тема</li></ul><a href="#brief" class="btn btn-main">Заказать</a></div>
		<div class="price-card"><h3 class="price-card-title">Премиум</h3><div class="price-value">от <strong>300 000</strong> ₽</div><ul class="price-features"><li>Неограниченно экранов</li><li>Дизайн-система</li><li>Адаптив под планшеты</li><li>Авторский надзор</li></ul><a href="#brief" class="btn btn-main">Заказать</a></div>
	</div></div><div class="wave-divider wave-dark" aria-hidden="true"><svg viewBox="0 0 1200 60" preserveAspectRatio="none"><path d="M0,30 C150,55 350,5 600,30 C850,55 1050,5 1200,30 L1200,60 L0,60 Z"></path></svg></div></section>
	<section class="faq section-dark"><div class="container"><div class="section-title-wrap"><h2 class="section-title">Частые вопросы</h2></div><div class="faq-list" itemscope itemtype="https://schema.org/FAQPage">
		<div class="faq-item" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question"><h3 class="faq-question" itemprop="name">Сколько стоит дизайн приложения?</h3><div class="faq-answer" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"><div class="faq-answer-text" itemprop="text">Базовый дизайн (до 10 экранов) — от 80 000 ₽. Полноценный дизайн для двух платформ — от 150 000 ₽. Премиум — от 300 000 ₽.</div></div></div>
		<div class="faq-item" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question"><h3 class="faq-question" itemprop="name">Что входит в дизайн приложения?</h3><div class="faq-answer" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"><div class="faq-answer-text" itemprop="text">Прототипы, UI-дизайн всех экранов, адаптация под iOS и Android, анимации, UI-кит и передача макетов разработчикам.</div></div></div>
		<div class="faq-item" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question"><h3 class="faq-question" itemprop="name">Сколько времени занимает дизайн?</h3><div class="faq-answer" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"><div class="faq-answer-text" itemprop="text">Базовый проект — 2-3 недели. Стандартный — 4-6 недель. Сложный с дизайн-системой — от 1,5 месяцев.</div></div></div>
		<div class="faq-item" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question"><h3 class="faq-question" itemprop="name">Вы делаете дизайн под обе платформы?</h3><div class="faq-answer" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"><div class="faq-answer-text" itemprop="text">Да, адаптируем дизайн под iOS (Human Interface) и Android (Material Design) — приложение выглядит родным на каждой платформе.</div></div></div>
		<div class="faq-item" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question"><h3 class="faq-question" itemprop="name">Даёте ли исходники?</h3><div class="faq-answer" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"><div class="faq-answer-text" itemprop="text">Да, передаём Figma, иконки SVG, шрифты и гайдлайн по использованию дизайн-системы.</div></div></div>
	</div></div><div class="wave-divider wave-accent" aria-hidden="true"><svg viewBox="0 0 1200 60" preserveAspectRatio="none"><path d="M0,30 C150,55 350,5 600,30 C850,55 1050,5 1200,30 L1200,60 L0,60 Z"></path></svg></div></section>
<?php require_once __DIR__ . '/../../includes/footer.php'; ?>
