<?php
require_once __DIR__ . '/../../config.php';
$pageTitle = 'Комплексное продвижение сайта под ключ — SEO, контекст, SMM | Bobr Studio';
$pageDesc = 'Комплексное продвижение сайтов под ключ: SEO-оптимизация, контекстная реклама, SMM, Яндекс Директ, аналитика. Работаем на результат — закажите продвижение!';
$ogImage = '/img/svg/promo.svg';
require_once __DIR__ . '/../../includes/header.php';
?>
<script type="application/ld+json">{ "@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Главная","item":"<?= SITE_URL ?>/"},{"@type":"ListItem","position":2,"name":"Продвижение","item":"<?= SITE_URL ?>/promo"}]}</script>
<script type="application/ld+json">{ "@context":"https://schema.org","@type":"Service","name":"Комплексное продвижение сайта","description":"SEO-продвижение, контекстная реклама, SMM, Яндекс Директ, аналитика и оптимизация.","provider":{"@type":"ProfessionalService","name":"Bobr Studio","url":"<?= SITE_URL ?>"},"areaServed":"RU","offers":{"@type":"Offer","price":"25000","priceCurrency":"RUB"}}</script>
	<section class="hero section-light"><canvas class="hero-particles" id="heroParticles" aria-hidden="true"></canvas><div class="container hero-grid"><div class="hero-content"><div class="slider-title">Комплексное<h1>Продвижение <span class="text-accent">сайта</span> под ключ</h1>— SEO, контекст, SMM и аналитика</div><p class="slider-text">Продвигаем сайты комплексно: SEO-оптимизация, контекстная реклама Яндекс Директ, SMM. Анализируем, настраиваем и оптимизируем — вы получаете рост трафика, лидов и продаж.</p><a href="#brief" class="btn btn-main">Заказать продвижение</a></div><div class="hero-image"><img src="/img/svg/promo.svg" alt="Продвижение сайта под ключ" loading="eager" style="max-height:550px;width:auto"></div></div><div class="wave-divider wave-dark" aria-hidden="true"><svg viewBox="0 0 1200 60" preserveAspectRatio="none"><path d="M0,30 C150,55 350,5 600,30 C850,55 1050,5 1200,30 L1200,60 L0,60 Z"></path></svg></div></section>
	<section class="stages section-dark"><div class="container"><div class="section-title-wrap"><h2 class="section-title">Этапы продвижения</h2></div><div class="stages-grid">
		<div class="stage-card dev-etap"><div class="stage-num">01</div><div class="stage-icon"><img loading="lazy" src="/img/icons/analise.png" alt="Аудит"></div><h3 class="stage-title">Аудит и аналитика</h3><ul><li>Анализируем сайт и конкурентов</li><li>Собираем семантику</li><li>Определяем точки роста</li><li>Стратегию согласовываем</li></ul></div>
		<div class="stage-card dev-etap"><div class="stage-num">02</div><div class="stage-icon"><img loading="lazy" src="/img/icons/seo.png" alt="SEO"></div><h3 class="stage-title">SEO-оптимизация</h3><ul><li>Технический аудит SEO</li><li>Оптимизация мета-тегов</li><li>Микроразметка и ЧПУ</li><li>Улучшение скорости</li></ul></div>
		<div class="stage-card dev-etap"><div class="stage-num">03</div><div class="stage-icon"><img loading="lazy" src="/img/icons/search.png" alt="Контекст"></div><h3 class="stage-title">Контекстная реклама</h3><ul><li>Яндекс Директ и Google Ads</li><li>Сбор семантического ядра</li><li>Настройка кампаний</li><li>Оптимизация ставок</li></ul></div>
		<div class="stage-card dev-etap"><div class="stage-num">04</div><div class="stage-icon"><img loading="lazy" src="/img/icons/chat.png" alt="SMM"></div><h3 class="stage-title">SMM продвижение</h3><ul><li>Ведение соцсетей</li><li>Таргетированная реклама</li><li>Контент-план</li><li>Работа с аудиторией</li></ul></div>
		<div class="stage-card dev-etap"><div class="stage-num">05</div><div class="stage-icon"><img loading="lazy" src="/img/icons/calculator.png" alt="Аналитика"></div><h3 class="stage-title">Аналитика и отчёты</h3><ul><li>Сквозная аналитика</li><li>Цели и конверсии</li><li>Ежемесячные отчёты</li><li>Корректировка стратегии</li></ul></div>
		<div class="stage-card dev-etap"><div class="stage-num">06</div><div class="stage-icon"><img loading="lazy" src="/img/icons/start.png" alt="Рост"></div><h3 class="stage-title">Масштабирование</h3><ul><li>A/B тесты и оптимизация</li><li>Увеличение рекламных бюджетов</li><li>Новые каналы трафика</li><li>Рост конверсии</li></ul></div>
	</div></div><div class="wave-divider wave-light" aria-hidden="true"><svg viewBox="0 0 1200 60" preserveAspectRatio="none"><path d="M0,30 C150,55 350,5 600,30 C850,55 1050,5 1200,30 L1200,60 L0,60 Z"></path></svg></div></section>
	<section class="advantages section-light"><div class="container"><div class="section-title-wrap"><h3 class="section-title">Почему заказывают продвижение у нас?</h3></div><div class="adv-grid">
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/search.png" alt="Комплексный подход"></div><h3 class="adv-title">Комплексный подход</h3><p class="adv-text">SEO + контекст + SMM + аналитика — все каналы работают в одной связке, а не по отдельности</p></div>
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/money.png" alt="Прозрачный бюджет"></div><h3 class="adv-title">Прозрачный бюджет</h3><p class="adv-text">вы точно знаете, куда уходят деньги: отдельно работы, отдельно рекламные бюджеты</p></div>
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/desctop.png" alt="Все каналы"></div><h3 class="adv-title">Все каналы трафика</h3><p class="adv-text">поиск, контекст, соцсети, медийка, email — подбираем каналы под вашу нишу</p></div>
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/calculator.png" alt="Аналитика"></div><h3 class="adv-title">Сквозная аналитика</h3><p class="adv-text">видим, сколько реальных продаж принёс каждый канал — от клика до оплаты</p></div>
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/links.png" alt="Отчёты"></div><h3 class="adv-title">Понятные отчёты</h3><p class="adv-text">каждый месяц — отчёт с KPI: трафик, позиции, лиды, конверсия, расходы</p></div>
		<div class="adv-card"><div class="adv-icon"><img loading="lazy" src="/img/icons/support.png" alt="Поддержка"></div><h3 class="adv-title">Поддержка и консультации</h3><p class="adv-text">отвечаем на вопросы, корректируем стратегию, ищем новые точки роста</p></div>
	</div></div><div class="wave-divider wave-dark" aria-hidden="true"><svg viewBox="0 0 1200 60" preserveAspectRatio="none"><path d="M0,30 C150,55 350,5 600,30 C850,55 1050,5 1200,30 L1200,60 L0,60 Z"></path></svg></div></section>
<?php $briefWave='wave-dark';$briefTitle='Бриф на комплексное продвижение';$briefSubtitle='Расскажите о проекте — подготовим стратегию';require __DIR__.'/../../briefs/promo-brief.php';?>
<?php $noWave=true;require_once __DIR__.'/../../includes/tech-marquee.php';?>
<?php $pfDarkBg=true;$pfTitle='Наше портфолио';$pfSubtitle='Более 30 проектов';require_once __DIR__.'/../../includes/portfolio-block.php';?>
	<section class="price section-light"><div class="container"><div class="section-title-wrap"><h2 class="section-title">Стоимость продвижения</h2><p class="section-subtitle">Выберите тариф</p></div><div class="price-grid">
		<div class="price-card"><h3 class="price-card-title">SEO-Старт</h3><div class="price-value">от <strong>15 000</strong> ₽/мес</div><ul class="price-features"><li>SEO-аудит и оптимизация</li><li>Сбор семантики</li><li>Технические доработки</li><li>Ежемесячный отчёт</li></ul><a href="#brief" class="btn btn-main">Заказать</a></div>
		<div class="price-card price-card-featured"><h3 class="price-card-title">Стандарт</h3><div class="price-value">от <strong>35 000</strong> ₽/мес</div><ul class="price-features"><li>SEO + контекстная реклама</li><li>Яндекс Директ + Google Ads</li><li>Настройка целей</li><li>Оптимизация бюджета</li><li>Еженедельные отчёты</li></ul><a href="#brief" class="btn btn-main">Заказать</a></div>
		<div class="price-card"><h3 class="price-card-title">Комплекс</h3><div class="price-value">от <strong>70 000</strong> ₽/мес</div><ul class="price-features"><li>SEO + контекст + SMM</li><li>Сквозная аналитика</li><li>Контент-маркетинг</li><li>Персональный менеджер</li><li>Приоритетная поддержка</li></ul><a href="#brief" class="btn btn-main">Заказать</a></div>
	</div></div><div class="wave-divider wave-dark" aria-hidden="true"><svg viewBox="0 0 1200 60" preserveAspectRatio="none"><path d="M0,30 C150,55 350,5 600,30 C850,55 1050,5 1200,30 L1200,60 L0,60 Z"></path></svg></div></section>
	<section class="faq section-dark"><div class="container"><div class="section-title-wrap"><h2 class="section-title">Частые вопросы</h2></div><div class="faq-list" itemscope itemtype="https://schema.org/FAQPage">
		<div class="faq-item" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question"><h3 class="faq-question" itemprop="name">Сколько стоит продвижение сайта?</h3><div class="faq-answer" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"><div class="faq-answer-text" itemprop="text">SEO-оптимизация — от 15 000 ₽/мес. SEO + контекстная реклама — от 35 000 ₽/мес. Комплекс с SMM и аналитикой — от 70 000 ₽/мес.</div></div></div>
		<div class="faq-item" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question"><h3 class="faq-question" itemprop="name">Какие каналы продвижения вы используете?</h3><div class="faq-answer" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"><div class="faq-answer-text" itemprop="text">SEO-оптимизация, Яндекс Директ, Google Ads, SMM, таргетинг, email-маркетинг, медийная реклама. Подбираем каналы под конкретную нишу.</div></div></div>
		<div class="faq-item" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question"><h3 class="faq-question" itemprop="name">Когда будут первые результаты?</h3><div class="faq-answer" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"><div class="faq-answer-text" itemprop="text">Контекстная реклама даёт заявки в первые дни. SEO — первые позиции через 2-4 месяца. SMM — рост подписчиков через 1-2 месяца.</div></div></div>
		<div class="faq-item" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question"><h3 class="faq-question" itemprop="name">Входит ли рекламный бюджет в стоимость?</h3><div class="faq-answer" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"><div class="faq-answer-text" itemprop="text">Нет, бюджет на клики оплачивается отдельно. Мы управляем им так, чтобы получить максимальный результат.</div></div></div>
		<div class="faq-item" itemscope itemprop="mainEntity" itemtype="https://schema.org/Question"><h3 class="faq-question" itemprop="name">Вы даёте гарантию на результат?</h3><div class="faq-answer" itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer"><div class="faq-answer-text" itemprop="text">Гарантируем профессиональный подход и прозрачную отчётность. Конкретные цифры зависят от ниши, конкурентов и продукта.</div></div></div>
	</div></div><div class="wave-divider wave-accent" aria-hidden="true"><svg viewBox="0 0 1200 60" preserveAspectRatio="none"><path d="M0,30 C150,55 350,5 600,30 C850,55 1050,5 1200,30 L1200,60 L0,60 Z"></path></svg></div></section>
<?php require_once __DIR__ . '/../../includes/footer.php'; ?>
